packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  "@biomejs/biome": ^1.9.4
  "@types/node": ^22
  lucide-react: ^0.460.0
  tailwindcss: ^3.4.15
  typescript: ^5.7.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
